// Mock Data for Movie Vault — realistic TMDB-shaped data for development

import { TMDBMovie, TMDBTVShow, CastMember } from '@/types/tmdb.types';
import { GENRE_MAP, TV_GENRE_MAP } from './constants';

// Helper to generate TMDB image URLs (these are real TMDB poster/backdrop paths from popular titles)
const POSTER_PLACEHOLDERS = [
  '/1E5baAaEse26fej7uHcjOgEERB2.jpg',
  '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
  '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  '/7WsyChQLEftFiDhRuCmGpQ1B2GY.jpg',
  '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
  '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
  '/sv1xJUazXeYqAyy0CJfhLGgkAyZ.jpg',
];

const BACKDROP_PLACEHOLDERS = [
  '/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
  '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
  '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
  '/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
];

export const MOCK_TRENDING_MOVIES: TMDBMovie[] = [
  {
    id: 299536,
    title: 'Avengers: Infinity War',
    original_title: 'Avengers: Infinity War',
    overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2018-04-25',
    vote_average: 8.3,
    vote_count: 27500,
    popularity: 350.5,
    genre_ids: [28, 12, 878],
    original_language: 'en',
    adult: false,
    video: false,
    media_type: 'movie',
  },
  {
    id: 299534,
    title: 'Avengers: Endgame',
    original_title: 'Avengers: Endgame',
    overview: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos\' actions.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2019-04-24',
    vote_average: 8.3,
    vote_count: 24000,
    popularity: 320.2,
    genre_ids: [28, 12, 878],
    original_language: 'en',
    adult: false,
    video: false,
    media_type: 'movie',
  },
  {
    id: 505642,
    title: 'Black Panther: Wakanda Forever',
    original_title: 'Black Panther: Wakanda Forever',
    overview: 'Queen Ramonda, Shuri, M\'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T\'Challa\'s death.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2022-11-09',
    vote_average: 7.3,
    vote_count: 5200,
    popularity: 280.1,
    genre_ids: [28, 12, 878],
    original_language: 'en',
    adult: false,
    video: false,
    media_type: 'movie',
  },
  {
    id: 438631,
    title: 'Dune',
    original_title: 'Dune',
    overview: 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '2021-09-15',
    vote_average: 7.8,
    vote_count: 10500,
    popularity: 310.7,
    genre_ids: [878, 12],
    original_language: 'en',
    adult: false,
    video: false,
    media_type: 'movie',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2023-07-19',
    vote_average: 8.1,
    vote_count: 8700,
    popularity: 450.3,
    genre_ids: [18, 36],
    original_language: 'en',
    adult: false,
    video: false,
    media_type: 'movie',
  },
  {
    id: 346698,
    title: 'Barbie',
    original_title: 'Barbie',
    overview: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2023-07-19',
    vote_average: 7.0,
    vote_count: 7300,
    popularity: 380.5,
    genre_ids: [35, 12, 14],
    original_language: 'en',
    adult: false,
    video: false,
    media_type: 'movie',
  },
];

export const MOCK_BOLLYWOOD_MOVIES: TMDBMovie[] = [
  {
    id: 614934,
    title: 'Pathaan',
    original_title: 'पठान',
    overview: 'An Indian spy takes on the leader of a group of mercenaries who have nefarious plans to target his homeland.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2023-01-25',
    vote_average: 6.7,
    vote_count: 400,
    popularity: 180.2,
    genre_ids: [28, 53, 12],
    original_language: 'hi',
    adult: false,
    video: false,
  },
  {
    id: 758323,
    title: 'The Kashmir Files',
    original_title: 'द कश्मीर फ़ाइल्स',
    overview: 'Based on the true events of the exodus of Kashmiri Hindus from the valley of Kashmir in 1990.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '2022-03-11',
    vote_average: 7.2,
    vote_count: 300,
    popularity: 155.3,
    genre_ids: [18, 36],
    original_language: 'hi',
    adult: false,
    video: false,
  },
  {
    id: 930564,
    title: 'Jawan',
    original_title: 'जवान',
    overview: 'A man is driven by a personal vendetta to rectify the wrongs in society, while being challenged by a ruthless outlaw.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '2023-09-07',
    vote_average: 7.1,
    vote_count: 350,
    popularity: 200.1,
    genre_ids: [28, 18, 53],
    original_language: 'hi',
    adult: false,
    video: false,
  },
  {
    id: 785084,
    title: 'RRR',
    original_title: 'RRR',
    overview: 'A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2022-03-24',
    vote_average: 7.8,
    vote_count: 1800,
    popularity: 220.4,
    genre_ids: [28, 18, 12],
    original_language: 'te',
    adult: false,
    video: false,
  },
  {
    id: 1008005,
    title: 'Animal',
    original_title: 'एनिमल',
    overview: 'The troubled relationship of a father and a son who share an untamed, unbridled and primal bond that cannot be contained.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2023-12-01',
    vote_average: 6.5,
    vote_count: 250,
    popularity: 175.8,
    genre_ids: [28, 80, 18],
    original_language: 'hi',
    adult: false,
    video: false,
  },
  {
    id: 700391,
    title: 'Brahmastra Part One: Shiva',
    original_title: 'ब्रह्मास्त्र भाग एक: शिवा',
    overview: 'Shiva discovers he has a mysterious connection to the Brahmastra, an ancient weapon of immense power tied to the elements of nature.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '2022-09-09',
    vote_average: 5.9,
    vote_count: 330,
    popularity: 145.6,
    genre_ids: [28, 14, 12],
    original_language: 'hi',
    adult: false,
    video: false,
  },
];

export const MOCK_TV_SHOWS: TMDBTVShow[] = [
  {
    id: 1396,
    name: 'Breaking Bad',
    original_name: 'Breaking Bad',
    overview: 'When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer, he turns to a life of crime to secure his family\'s financial future.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2008-01-20',
    vote_average: 8.9,
    vote_count: 14000,
    popularity: 280.5,
    genre_ids: [18, 80],
    original_language: 'en',
    origin_country: ['US'],
    media_type: 'tv',
    number_of_seasons: 5,
    number_of_episodes: 62,
  },
  {
    id: 94997,
    name: 'House of the Dragon',
    original_name: 'House of the Dragon',
    overview: 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most combatants combust before the first... dragonfire.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2022-08-21',
    vote_average: 8.4,
    vote_count: 4500,
    popularity: 350.2,
    genre_ids: [10765, 18, 10759],
    original_language: 'en',
    origin_country: ['US'],
    media_type: 'tv',
    number_of_seasons: 2,
    number_of_episodes: 18,
  },
  {
    id: 1399,
    name: 'Game of Thrones',
    original_name: 'Game of Thrones',
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    first_air_date: '2011-04-17',
    vote_average: 8.4,
    vote_count: 22000,
    popularity: 420.1,
    genre_ids: [10765, 18, 10759],
    original_language: 'en',
    origin_country: ['US'],
    media_type: 'tv',
    number_of_seasons: 8,
    number_of_episodes: 73,
  },
  {
    id: 76479,
    name: 'The Boys',
    original_name: 'The Boys',
    overview: 'A group of vigilantes known informally as "The Boys" set out to take down corrupt superheroes who abuse their superpowers.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    first_air_date: '2019-07-25',
    vote_average: 8.5,
    vote_count: 9500,
    popularity: 310.4,
    genre_ids: [10765, 10759],
    original_language: 'en',
    origin_country: ['US'],
    media_type: 'tv',
    number_of_seasons: 4,
    number_of_episodes: 32,
  },
  {
    id: 93405,
    name: 'Squid Game',
    original_name: '오징어 게임',
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2021-09-17',
    vote_average: 7.8,
    vote_count: 13500,
    popularity: 500.3,
    genre_ids: [10759, 9648, 18],
    original_language: 'ko',
    origin_country: ['KR'],
    media_type: 'tv',
    number_of_seasons: 2,
    number_of_episodes: 16,
  },
  {
    id: 66732,
    name: 'Stranger Things',
    original_name: 'Stranger Things',
    overview: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2016-07-15',
    vote_average: 8.6,
    vote_count: 17000,
    popularity: 390.2,
    genre_ids: [18, 10765, 9648],
    original_language: 'en',
    origin_country: ['US'],
    media_type: 'tv',
    number_of_seasons: 4,
    number_of_episodes: 34,
  },
];

export const MOCK_ANIME: TMDBTVShow[] = [
  {
    id: 37854,
    name: 'One Piece',
    original_name: 'ワンピース',
    overview: 'Years ago, the fearsome Pirate King, Gol D. Roger, was executed leaving a huge pile of treasure and the famous "One Piece" behind.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '1999-10-20',
    vote_average: 8.7,
    vote_count: 4500,
    popularity: 310.5,
    genre_ids: [16, 10759, 35],
    original_language: 'ja',
    origin_country: ['JP'],
    number_of_seasons: 21,
    number_of_episodes: 1100,
  },
  {
    id: 85937,
    name: 'Demon Slayer',
    original_name: '鬼滅の刃',
    overview: 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2019-04-06',
    vote_average: 8.7,
    vote_count: 5800,
    popularity: 290.3,
    genre_ids: [16, 10759, 10765],
    original_language: 'ja',
    origin_country: ['JP'],
    number_of_seasons: 4,
    number_of_episodes: 55,
  },
  {
    id: 31911,
    name: 'Naruto Shippūden',
    original_name: 'ナルト 疾風伝',
    overview: 'Naruto Shippūden is the continuation of the original animated TV series Naruto. The story revolves around an older and slightly more mature Uzumaki Naruto.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2007-02-15',
    vote_average: 8.6,
    vote_count: 4000,
    popularity: 250.8,
    genre_ids: [16, 10759, 35],
    original_language: 'ja',
    origin_country: ['JP'],
    number_of_seasons: 20,
    number_of_episodes: 500,
  },
  {
    id: 1429,
    name: 'Attack on Titan',
    original_name: '進撃の巨人',
    overview: 'Several hundred years ago, humans were nearly exterminated by Titans. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    first_air_date: '2013-04-07',
    vote_average: 8.7,
    vote_count: 6500,
    popularity: 340.1,
    genre_ids: [16, 10765, 10759, 18],
    original_language: 'ja',
    origin_country: ['JP'],
    number_of_seasons: 4,
    number_of_episodes: 94,
  },
  {
    id: 62104,
    name: 'Jujutsu Kaisen',
    original_name: '呪術廻戦',
    overview: 'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    first_air_date: '2020-10-03',
    vote_average: 8.6,
    vote_count: 3700,
    popularity: 270.4,
    genre_ids: [16, 10759, 10765],
    original_language: 'ja',
    origin_country: ['JP'],
    number_of_seasons: 2,
    number_of_episodes: 47,
  },
  {
    id: 60625,
    name: 'Dragon Ball Super',
    original_name: 'ドラゴンボール超（スーパー）',
    overview: 'With Majin Boo defeated half a year prior, peace returns to Earth, where Son Goku now works as a radish farmer.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    first_air_date: '2015-07-05',
    vote_average: 7.4,
    vote_count: 3200,
    popularity: 200.6,
    genre_ids: [16, 10759, 35, 10765],
    original_language: 'ja',
    origin_country: ['JP'],
    number_of_seasons: 5,
    number_of_episodes: 131,
  },
];

export const MOCK_TOP_RATED_MOVIES: TMDBMovie[] = [
  {
    id: 278,
    title: 'The Shawshank Redemption',
    original_title: 'The Shawshank Redemption',
    overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '1994-09-23',
    vote_average: 8.7,
    vote_count: 26000,
    popularity: 160.5,
    genre_ids: [18, 80],
    original_language: 'en',
    adult: false,
    video: false,
  },
  {
    id: 238,
    title: 'The Godfather',
    original_title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '1972-03-14',
    vote_average: 8.7,
    vote_count: 20000,
    popularity: 140.2,
    genre_ids: [18, 80],
    original_language: 'en',
    adult: false,
    video: false,
  },
  {
    id: 240,
    title: 'The Godfather Part II',
    original_title: 'The Godfather Part II',
    overview: 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '1974-12-20',
    vote_average: 8.6,
    vote_count: 12000,
    popularity: 100.3,
    genre_ids: [18, 80],
    original_language: 'en',
    adult: false,
    video: false,
  },
  {
    id: 424,
    title: "Schindler's List",
    original_title: "Schindler's List",
    overview: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '1993-12-15',
    vote_average: 8.6,
    vote_count: 15000,
    popularity: 120.1,
    genre_ids: [18, 36, 10752],
    original_language: 'en',
    adult: false,
    video: false,
  },
  {
    id: 19404,
    title: 'Dilwale Dulhania Le Jayenge',
    original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
    overview: 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who values Indian traditions.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '1995-10-20',
    vote_average: 8.0,
    vote_count: 3500,
    popularity: 90.5,
    genre_ids: [35, 18, 10749],
    original_language: 'hi',
    adult: false,
    video: false,
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    original_title: 'Pulp Fiction',
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    release_date: '1994-09-10',
    vote_average: 8.5,
    vote_count: 27000,
    popularity: 130.8,
    genre_ids: [53, 80],
    original_language: 'en',
    adult: false,
    video: false,
  },
];

export const MOCK_CAST: CastMember[] = [
  { id: 1, name: 'Robert Downey Jr.', character: 'Tony Stark / Iron Man', profile_path: '/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg', order: 0, known_for_department: 'Acting' },
  { id: 2, name: 'Chris Evans', character: 'Steve Rogers / Captain America', profile_path: '/3bOGNsHlrswhyW79uvIHH1V43JI.jpg', order: 1, known_for_department: 'Acting' },
  { id: 3, name: 'Scarlett Johansson', character: 'Natasha Romanoff / Black Widow', profile_path: '/6NsMbJXRlDZuDzatN2akFY8J3MV.jpg', order: 2, known_for_department: 'Acting' },
  { id: 4, name: 'Chris Hemsworth', character: 'Thor', profile_path: '/piEmFxqvsgRTceqpCM5cnpYMlhP.jpg', order: 3, known_for_department: 'Acting' },
  { id: 5, name: 'Mark Ruffalo', character: 'Bruce Banner / Hulk', profile_path: '/z3dvKqMNDQWk3QLKzNkm1O1GPT2.jpg', order: 4, known_for_department: 'Acting' },
  { id: 6, name: 'Jeremy Renner', character: 'Clint Barton / Hawkeye', profile_path: '/yB84D1neTYXHAjDPiLEjzHPEilB.jpg', order: 5, known_for_department: 'Acting' },
  { id: 7, name: 'Tom Holland', character: 'Peter Parker / Spider-Man', profile_path: '/bBRlrpJm9XkNSg0YT5LCaxqoFMX.jpg', order: 6, known_for_department: 'Acting' },
  { id: 8, name: 'Chadwick Boseman', character: "T'Challa / Black Panther", profile_path: '/nL64XkwS5EhGkjRSmSitSqKssCm.jpg', order: 7, known_for_department: 'Acting' },
];

export function getGenreName(id: number): string {
  return GENRE_MAP[id] || TV_GENRE_MAP[id] || 'Unknown';
}

export function getGenreNames(ids: number[]): string[] {
  return ids.map(id => getGenreName(id)).filter(name => name !== 'Unknown');
}

export function getYear(dateStr: string): string {
  return dateStr ? dateStr.split('-')[0] : 'TBA';
}
