// Complete Taxonomy Tree for Streaming Platform (Movies, TV, Anime, Documentaries & Smart Tags)

export interface SubCategory {
  name: string;
  slug: string;
}

export interface Category {
  name: string;
  slug: string;
  subcategories: SubCategory[];
}

export const MOVIES_TAXONOMY: Category[] = [
  {
    name: 'Action & Adventure',
    slug: 'action-adventure',
    subcategories: [
      { name: 'Action Comedies', slug: 'action-comedies' },
      { name: 'Action Sci-Fi & Fantasy', slug: 'action-sci-fi-fantasy' },
      { name: 'Action Thrillers', slug: 'action-thrillers' },
      { name: 'Adventures', slug: 'adventures' },
      { name: 'Asian Action Movies', slug: 'asian-action' },
      { name: 'Classic Action & Adventure', slug: 'classic-action' },
      { name: 'Comic Book & Superhero Movies', slug: 'superhero' },
      { name: 'Crime Action & Adventure', slug: 'crime-action' },
      { name: 'Foreign Action & Adventure', slug: 'foreign-action' },
      { name: 'Hijacking Movies', slug: 'hijacking' },
      { name: 'Martial Arts Movies', slug: 'martial-arts' },
      { name: 'Military Action & Adventure', slug: 'military-action' },
      { name: 'Spy Action & Adventure', slug: 'spy-action' },
      { name: 'Westerns', slug: 'westerns' },
    ],
  },
  {
    name: 'Comedies',
    slug: 'comedies',
    subcategories: [
      { name: 'Dark Comedies', slug: 'dark-comedies' },
      { name: 'Foreign Comedies', slug: 'foreign-comedies' },
      { name: 'Horror Comedies', slug: 'horror-comedies' },
      { name: 'Late Night Comedies', slug: 'late-night-comedies' },
      { name: 'Mockumentaries', slug: 'mockumentaries' },
      { name: 'Musical Comedies', slug: 'musical-comedies' },
      { name: 'Political Comedies', slug: 'political-comedies' },
      { name: 'Romantic Comedies', slug: 'romantic-comedies' },
      { name: 'Satires', slug: 'satires' },
      { name: 'Screwball Comedies', slug: 'screwball-comedies' },
      { name: 'Slapstick Comedies', slug: 'slapstick-comedies' },
      { name: 'Sports Comedies', slug: 'sports-comedies' },
      { name: 'Stand-up Comedy', slug: 'stand-up-comedy' },
      { name: 'Teen Comedies', slug: 'teen-comedies' },
    ],
  },
  {
    name: 'Dramas',
    slug: 'dramas',
    subcategories: [
      { name: 'Biographical Dramas', slug: 'biographical-dramas' },
      { name: 'Classic Dramas', slug: 'classic-dramas' },
      { name: 'Crime Dramas', slug: 'crime-dramas' },
      { name: 'Dramas Based on Books', slug: 'dramas-books' },
      { name: 'Dramas Based on Real Life', slug: 'dramas-real-life' },
      { name: 'Epics', slug: 'epics' },
      { name: 'Independent Dramas', slug: 'independent-dramas' },
      { name: 'LGBTQ+ Dramas', slug: 'lgbtq-dramas' },
      { name: 'Military Dramas', slug: 'military-dramas' },
      { name: 'Political Dramas', slug: 'political-dramas' },
      { name: 'Romantic Dramas', slug: 'romantic-dramas' },
      { name: 'Showbiz Dramas', slug: 'showbiz-dramas' },
      { name: 'Social Issue Dramas', slug: 'social-issue-dramas' },
      { name: 'Tearjerkers', slug: 'tearjerkers' },
      { name: 'Teen Dramas', slug: 'teen-dramas' },
    ],
  },
  {
    name: 'Horror Movies',
    slug: 'horror',
    subcategories: [
      { name: 'Classic Horror', slug: 'classic-horror' },
      { name: 'Creature Features', slug: 'creature-features' },
      { name: 'Foreign Horror', slug: 'foreign-horror' },
      { name: 'Horror Comedies', slug: 'horror-comedies-movie' },
      { name: 'Monster Movies', slug: 'monster-movies' },
      { name: 'Psychological Horror', slug: 'psychological-horror' },
      { name: 'Satanic Stories', slug: 'satanic-stories' },
      { name: 'Slasher & Serial Killer', slug: 'slasher' },
      { name: 'Supernatural Horror', slug: 'supernatural-horror' },
      { name: 'Teen Screams', slug: 'teen-screams' },
      { name: 'Vampire Horror', slug: 'vampire-horror' },
      { name: 'Werewolf Horror', slug: 'werewolf-horror' },
      { name: 'Zombie Horror', slug: 'zombie-horror' },
    ],
  },
  {
    name: 'Sci-Fi & Fantasy',
    slug: 'sci-fi-fantasy',
    subcategories: [
      { name: 'Action Sci-Fi & Fantasy', slug: 'action-scifi-fantasy' },
      { name: 'Alien Sci-Fi', slug: 'alien-scifi' },
      { name: 'Classic Sci-Fi & Fantasy', slug: 'classic-scifi-fantasy' },
      { name: 'Comic Book & Superhero', slug: 'superhero-scifi' },
      { name: 'Cult Sci-Fi & Fantasy', slug: 'cult-scifi' },
      { name: 'Fantasy Movies', slug: 'fantasy-movies-list' },
      { name: 'Foreign Sci-Fi & Fantasy', slug: 'foreign-scifi' },
      { name: 'Monster Movies', slug: 'monster-scifi' },
      { name: 'Sci-Fi Adventure', slug: 'scifi-adventure' },
      { name: 'Sci-Fi Dramas', slug: 'scifi-dramas' },
      { name: 'Sci-Fi Horror', slug: 'scifi-horror' },
      { name: 'Sci-Fi Thrillers', slug: 'scifi-thrillers' },
    ],
  },
  {
    name: 'Romantic Movies',
    slug: 'romance',
    subcategories: [
      { name: 'Classic Romantic Movies', slug: 'classic-romance' },
      { name: 'Quirky Romance', slug: 'quirky-romance' },
      { name: 'Romantic Comedies', slug: 'rom-coms' },
      { name: 'Romantic Dramas', slug: 'rom-dramas' },
      { name: 'Romantic Favorites', slug: 'romantic-favorites' },
      { name: 'Romantic Foreign Movies', slug: 'romantic-foreign' },
      { name: 'Romantic Independent Movies', slug: 'romantic-independent' },
      { name: 'Steamy Romantic Movies', slug: 'steamy-romance' },
    ],
  },
  {
    name: 'Thrillers & Mystery',
    slug: 'thriller-mystery',
    subcategories: [
      { name: 'Action Thrillers', slug: 'action-thrillers-list' },
      { name: 'Classic Thrillers', slug: 'classic-thrillers' },
      { name: 'Crime Thrillers', slug: 'crime-thrillers' },
      { name: 'Foreign Thrillers', slug: 'foreign-thrillers' },
      { name: 'Gangster Movies', slug: 'gangster-movies' },
      { name: 'Independent Thrillers', slug: 'independent-thrillers' },
      { name: 'Mysteries', slug: 'mysteries' },
      { name: 'Political Thrillers', slug: 'political-thrillers' },
      { name: 'Psychological Thrillers', slug: 'psychological-thrillers' },
      { name: 'Sci-Fi Thrillers', slug: 'scifi-thrillers-list' },
      { name: 'Spy Thrillers', slug: 'spy-thrillers' },
      { name: 'Steamy Thrillers', slug: 'steamy-thrillers' },
      { name: 'Supernatural Thrillers', slug: 'supernatural-thrillers' },
    ],
  },
  {
    name: 'Documentaries',
    slug: 'documentaries',
    subcategories: [
      { name: 'Biographical Documentaries', slug: 'biography-docs' },
      { name: 'Crime Documentaries', slug: 'crime-docs' },
      { name: 'Foreign Documentaries', slug: 'foreign-docs' },
      { name: 'Historical Documentaries', slug: 'historical-docs' },
      { name: 'Military Documentaries', slug: 'military-docs' },
      { name: 'Mockumentaries', slug: 'mock-docs' },
      { name: 'Music & Concert Documentaries', slug: 'music-docs' },
      { name: 'Political Documentaries', slug: 'political-docs' },
      { name: 'Religious Documentaries', slug: 'religious-docs' },
      { name: 'Science & Nature Documentaries', slug: 'nature-docs' },
      { name: 'Social & Cultural Documentaries', slug: 'social-docs' },
      { name: 'Spiritual Documentaries', slug: 'spiritual-docs' },
      { name: 'Sports Documentaries', slug: 'sports-docs' },
      { name: 'Travel & Adventure Documentaries', slug: 'travel-docs' },
    ],
  },
  {
    name: 'Children & Family Movies',
    slug: 'family',
    subcategories: [
      { name: 'Animal Tales', slug: 'animal-tales' },
      { name: 'Disney', slug: 'disney-movies' },
      { name: 'Education for Kids', slug: 'kids-education' },
      { name: 'Family Features', slug: 'family-features' },
      { name: 'Kids Music', slug: 'kids-music' },
      { name: 'Movies Based on Children\'s Books', slug: 'kids-book-movies' },
      { name: 'Movies for Ages 0-2', slug: 'movies-ages-0-2' },
      { name: 'Movies for Ages 2-4', slug: 'movies-ages-2-4' },
      { name: 'Movies for Ages 5-7', slug: 'movies-ages-5-7' },
      { name: 'Movies for Ages 8-10', slug: 'movies-ages-8-10' },
      { name: 'Movies for Ages 11-12', slug: 'movies-ages-11-12' },
      { name: 'TV Cartoons', slug: 'tv-cartoons' },
    ],
  },
];

export const TV_TAXONOMY: Category[] = [
  {
    name: 'By Genre',
    slug: 'tv-genre',
    subcategories: [
      { name: 'TV Action & Adventure', slug: 'tv-action-adventure' },
      { name: 'TV Comedies', slug: 'tv-comedies' },
      { name: 'Sitcoms', slug: 'tv-sitcoms' },
      { name: 'Sketch Comedy', slug: 'tv-sketch' },
      { name: 'Animated Comedies', slug: 'tv-animated-comedy' },
      { name: 'Teen Comedies', slug: 'tv-teen-comedy' },
      { name: 'TV Dramas', slug: 'tv-dramas' },
      { name: 'Crime Dramas', slug: 'tv-crime-dramas' },
      { name: 'Family Dramas', slug: 'tv-family-dramas' },
      { name: 'Medical Dramas', slug: 'tv-medical' },
      { name: 'Legal Dramas', slug: 'tv-legal' },
      { name: 'Political Dramas', slug: 'tv-political' },
      { name: 'Teen Dramas', slug: 'tv-teen-drama' },
      { name: 'Soap Operas', slug: 'tv-soaps' },
      { name: 'TV Horror', slug: 'tv-horror' },
      { name: 'TV Mysteries', slug: 'tv-mysteries' },
      { name: 'TV Sci-Fi & Fantasy', slug: 'tv-scifi-fantasy' },
      { name: 'TV Thrillers', slug: 'tv-thrillers' },
      { name: 'TV Documentaries', slug: 'tv-docs' },
    ],
  },
  {
    name: 'By Format',
    slug: 'tv-format',
    subcategories: [
      { name: 'Miniseries (Limited Series)', slug: 'tv-miniseries' },
      { name: 'Anthology Series', slug: 'tv-anthologies' },
      { name: 'Procedural Series', slug: 'tv-procedural' },
      { name: 'Serialized Dramas', slug: 'tv-serialized' },
      { name: 'Reality TV', slug: 'tv-reality' },
      { name: 'Competition Shows', slug: 'tv-competition' },
      { name: 'Dating Shows', slug: 'tv-dating' },
      { name: 'Makeover Shows', slug: 'tv-makeover' },
      { name: 'Survival Shows', slug: 'tv-survival' },
      { name: 'Talk Shows & Variety', slug: 'tv-talk-shows' },
      { name: 'Game Shows', slug: 'tv-game-shows' },
      { name: 'News & Current Affairs', slug: 'tv-news' },
      { name: 'Kids\' TV Shows', slug: 'tv-kids' },
    ],
  },
  {
    name: 'By Region/Language',
    slug: 'tv-region',
    subcategories: [
      { name: 'British TV Shows', slug: 'tv-british' },
      { name: 'Korean TV Shows (K-Dramas)', slug: 'tv-korean' },
      { name: 'Japanese TV Shows', slug: 'tv-japanese' },
      { name: 'Indian TV Shows', slug: 'tv-indian' },
      { name: 'Spanish-Language TV Shows', slug: 'tv-spanish' },
      { name: 'French TV Shows', slug: 'tv-french' },
      { name: 'German TV Shows', slug: 'tv-german' },
      { name: 'Turkish TV Shows', slug: 'tv-turkish' },
      { name: 'Other International Series', slug: 'tv-international' },
    ],
  },
  {
    name: 'By Audience',
    slug: 'tv-audience',
    subcategories: [
      { name: 'TV for Kids (Ages 2-7)', slug: 'tv-kids-2-7' },
      { name: 'TV for Tweens (Ages 8-12)', slug: 'tv-tweens-8-12' },
      { name: 'Teen TV Shows', slug: 'tv-teens' },
      { name: 'Family-Friendly TV', slug: 'tv-family' },
      { name: 'Adult Animation', slug: 'tv-adult-animation' },
      { name: 'Mature Audiences (TV-MA)', slug: 'tv-ma' },
    ],
  },
];

export const ANIME_TAXONOMY: Category[] = [
  {
    name: 'By Genre',
    slug: 'anime-genre',
    subcategories: [
      { name: 'Anime Action', slug: 'anime-action' },
      { name: 'Anime Comedies', slug: 'anime-comedies' },
      { name: 'Anime Dramas', slug: 'anime-dramas' },
      { name: 'Anime Fantasy', slug: 'anime-fantasy' },
      { name: 'Anime Horror', slug: 'anime-horror' },
      { name: 'Anime Romance', slug: 'anime-romance' },
      { name: 'Anime Sci-Fi', slug: 'anime-scifi' },
      { name: 'Anime Thrillers', slug: 'anime-thrillers' },
      { name: 'Slice of Life Anime', slug: 'anime-slice-of-life' },
    ],
  },
  {
    name: 'By demographic',
    slug: 'anime-demographic',
    subcategories: [
      { name: 'Shonen', slug: 'anime-shonen' },
      { name: 'Shojo', slug: 'anime-shojo' },
      { name: 'Seinen', slug: 'anime-seinen' },
      { name: 'Josei', slug: 'anime-josei' },
      { name: 'Kodomo', slug: 'anime-kodomo' },
    ],
  },
  {
    name: 'By Theme',
    slug: 'anime-theme',
    subcategories: [
      { name: 'Mecha Anime', slug: 'anime-mecha' },
      { name: 'Isekai (Another World)', slug: 'anime-isekai' },
      { name: 'Magical Girl', slug: 'anime-magical-girl' },
      { name: 'Sports Anime', slug: 'anime-sports' },
      { name: 'School Life', slug: 'anime-school-life' },
      { name: 'Historical Anime', slug: 'anime-historical' },
      { name: 'Supernatural Anime', slug: 'anime-supernatural' },
      { name: 'Psychological Anime', slug: 'anime-psychological' },
      { name: 'Harem/Romance Comedy', slug: 'anime-harem-romcom' },
    ],
  },
];

export const SMART_TAGS = {
  mood: ['Feel-Good', 'Dark', 'Suspenseful', 'Inspirational', 'Mind-Bending', 'Heartfelt', 'Witty', 'Intense', 'Relaxing', 'Thought-Provoking', 'Quirky', 'Epic'],
  theme: ['Coming of Age', 'Revenge', 'Redemption', 'Survival', 'Friendship', 'Family', 'Love Triangle', 'Heist', 'Time Travel', 'AI & Robotics', 'Climate Change', 'Social Justice', 'Underdog Story', 'Betrayal'],
  production: ['Award-Winning', 'Critically Acclaimed', 'Cult Classic', 'Hidden Gem', 'Box Office Hit', 'Festival Selection', 'Remake', 'Based on True Story', 'Based on Book/Comic'],
  technical: ['4K UHD', 'HDR', 'Dolby Atmos', '5.1 Surround', 'Black & White', 'Silent', 'Restored', 'Director\'s Cut'],
  accessibility: ['Audio Description', 'Closed Captions', 'Sign Language', 'Easy-to-Follow', 'Descriptive Subtitles'],
};
